server:
  port: 9218

mqtt:
  mode: 0
  server: tcp://192.168.1.103:1883
  #  internal-server: tcp://172.17.74.195:1884
  client-id: eventbus24
  cleanSession: true
  connectionTimeout: 5
  keepAliveInterval: 20

spring:
  redis:
    database: 1
    host: 192.168.1.100
    port: 6379
    password: songof123
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  datasource:
    tdengine-server:
      driver-class-name: com.taosdata.jdbc.TSDBDriver
      jdbc-url: jdbc:TAOS://82.156.191.186:6030/td_edge_camera?timezone=Asia/Beijing&charset=utf-8
      username: root
      password: taosdata
      type: com.zaxxer.hikari.HikariDataSource      # Hikari连接池的设置
      minimum-idle: 5                 #最小连接
      maximum-pool-size: 15        #最大连接
      auto-commit: true        #自动提交
      idle-timeout: 30000        #最大空闲时常
      pool-name: TDengineHikariCP        #连接池名
      max-lifetime: 1800000        #最大生命周期
      connection-timeout: 30000        #连接超时时间
      connection-test-query: show tables
    mysql-server:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.1.100:3306/iot_cloud_sys?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
      username: root
      password: songof123
      type: com.zaxxer.hikari.HikariDataSource      # Hikari连接池的设置
      minimum-idle: 5                 #最小连接
      maximum-pool-size: 15        #最大连接
      auto-commit: true        #自动提交
      idle-timeout: 30000        #最大空闲时常
      pool-name: DatebookHikariCP        #连接池名
      max-lifetime: 1800000        #最大生命周期
      connection-timeout: 30000        #连接超时时间
mybatis:
  typeAliasesPackage: com.taosdata.jdbc.springbootdemo.domain
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #打印sql
    call-setters-on-nulls: true  #设置查询字段为空时，也返回该字段
    map-underscore-to-camel-case: true
rocketmq:
  producer:
    isOnOff: on
    groupName: device-data-producer
    namesrvAddr: 192.168.1.100:9876
    maxMessageSize: 4096
    sendMsgTimeOut: 3000
    retryTimesWhenSendFailed: 2
  consumer:
    isOnOff: on
    groupName: device-data-consumer
    namesrvAddr: 192.168.1.100:9876
    topics: walks-bodyInfo,*
    consumeThreadMin: 5
    consumeThreadMax: 32
    consumeMessageBatchMaxSize: 1
kafka:
  consumer:
    srvAddr: 127.0.0.1:9092
    groupId: default_consumer_group

